### ISSUE TITLE
The plugin com.github.eirslett:frontend-maven-plugin:0.0.23 requires Maven version 3.1.0

### ISSUE THREAD

**Issue by levrun** [Robert-Leggett/angular_bootstrap_spring#5]
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:install-node-and-npm (install node and npm) on project client: The plugin com.github.eirslett:frontend-maven-plugin:0.0.23 requires Maven version 3.1.0 -> [Help 1]
[ERROR] 

How I can do it without Maven 3.10?
PS:
I the latest Maven installed 3.3.3

**Comment by Robert-Leggett** [comment]
Seems a duplicate of issue 3.

Im going to close this issue.
